### ISSUE TITLE
Regions are displayed twice in the list

### ISSUE THREAD

**Issue by Cerbere64** [oleg-shilo/PyMap.VSIX#12]
Hello,

It seems that there is a bug in diplaying region. All the regions are added a second time at the end of the list :
![image](https://github.com/oleg-shilo/PyMap.VSIX/assets/49989377/9b6569c1-6d07-49ae-bcad-0bb60d7576be)

Anyway, great work and thanks a lot for this amazing tool.

**Comment by oleg-shilo** [comment]
Yes, it is a defect.
Thank you for reporting it.
Fill do the fix shortly.

**Comment by oleg-shilo** [comment]
Done, fixed in v2.1.6.
It was a silly mistake in the region-handling algorithm.

Please update via the extension manager.

**Comment by Cerbere64** [comment]
It seems to be good !
Thanks a lot.
