### ISSUE TITLE
Horizontal Scroll Jumps on Document Load

### ISSUE THREAD

**Issue by bfarrall** [oleg-shilo/PyMap.VSIX#13]
Methods in the codemap now show the list of parameters, but now what can happen is the scroll bar will jump to display the end of a method parameter list for the last selected method in the class.

Steps:
- turn on auto sync
- open class
- select method with long signature
- navigate to a different class
- select a property
- navigate back to original class
- codemap scroll bar jumps to right after it syncs and selects the method again

**Comment by oleg-shilo** [comment]
Can you help me to reproduce it?

The steps you provided do not seem to trigger the problem. Maybe something is missing in the steps....
But after switching between classes I do not see h-scrollbar changing its position.

![capture](https://github.com/oleg-shilo/PyMap.VSIX/assets/16729806/5ab23bbd-cb2e-47be-84b2-085ffdde35f2)

**Comment by bfarrall** [comment]
In my situation I had methods with quite long signatures. Some more than 10
(don't ask). It seemed to only happen for those extra long ones.

**Comment by oleg-shilo** [comment]
Done.

This problem happens only if the vertical scrollbar is visible and not at the 0 position.
The problem itself is the intended behaviour implemented by ListBox. Though it is not convenient for our use case. 
Thus now I am changing the H-scroll position on selection change to most-left.

**Comment by bfarrall** [comment]
Interesting to hear the issue I can see why the listbox would need such a mechanic. The latest fix for the codemap looks like it corrected the issue for me. Thanks!

**Comment by oleg-shilo** [comment]
> ... I can see why the listbox would need such a mechanic.

Yes, I cannot say that it is wrong. The developer asks ListBox to show the selection, but the selection does not fit the visible area. Which part selection to show? Does not what you decide to show, there will be cases when your decision will not give the user the best UI (our case).

BTW, the same applies to the "show selection" in the TexBox API. Is it the selection start or the end? :o)
