### ISSUE TITLE
Feature Request - toggle option for method signatures

### ISSUE THREAD

**Issue by bfarrall** [oleg-shilo/PyMap.VSIX#14]
It would be really handy to have an additional filter option to turn off the method signatures. This can be useful if there are methods with very long signatures that require scrolling.

**Comment by oleg-shilo** [comment]
Agree. Good idea. 
Changing it to 'Enhancement'.

**Comment by oleg-shilo** [comment]
Done.
Will be available in the very next release after #13 is resolved.

![image](https://github.com/oleg-shilo/PyMap.VSIX/assets/16729806/8544924a-bc74-45dd-8bd0-67015614e5d0)

**Comment by bfarrall** [comment]
This looks very clean, I appreciate you've left the ellipse for a visual still.

**Comment by bfarrall** [comment]
This looks very clean, I appreciate you've left the ellipse for a visual still.
