### ISSUE TITLE
Feature Request - Toggle option for sync action

### ISSUE THREAD

**Issue by bfarrall** [oleg-shilo/PyMap.VSIX#15]
It would be great to have the ability to toggle when the codemap keeps in sync.

Default - map syncs with movement cursor in class
Alt - map doesn't sync and loads normally but scrolled to top

**Comment by bfarrall** [comment]
user issue - i'm blind this exists.

**Comment by oleg-shilo** [comment]
All good. 
You still can take credit for validating the UX requirement for me. :o)
