### ISSUE TITLE
Cannot install in latest codium

### ISSUE THREAD

**Issue by nicolashainaux** [oleg-shilo/PyMap.VSIX#2]
Hello, when I tried to install this extension in the latest [codium](https://vscodium.com/) (the "free, open sourced binary of vscode"), I got:

```
$ codium --install-extension PyMap.vsix 
Installing extensions...
extension/package.json not found inside zip.
Failed Installing Extensions: file:///home/nico/Downloads/PyMap.vsix
```
And indeed, there's no `package.json` in the vsix file.

Latest codium info:
```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-19T00:58:08.152Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.4.0-122-generic
```

(I tried this way because it does not show up when searching the extensions from codium directly, so I downloaded it from https://marketplace.visualstudio.com/items?itemName=OlegShilo.PyMap).
(I am testing codium because of atom's planned sunset, but codium is missing such a compulsory feature; it was only available as extension in atom too)

**Comment by oleg-shilo** [comment]
Sorry, it is a Visual Studio but not VSCode extension.

Though I have ported (and extended) this extension for VSCode too. See this link: https://marketplace.visualstudio.com/items?itemName=oleg-shilo.codemap

**Comment by nicolashainaux** [comment]
OK, so I guess codemap is the extension I actually want. I don't know about the different versions of vscode / visual studio etc.
I have another question then, but this will be about codemap, so I'll open an issue there.
Thank you very much!

**Comment by nicolashainaux** [comment]
Well, finally I could install codemap from the release file: `codium --install-extension codemap-1.16.3.vsix` so there's no issue to open there!
Thank you very much for this practical extension. I could not use codium without it, for sure. Cannot understand such a feature is not included by default, actually.

**Comment by oleg-shilo** [comment]
Gald it all worked out after all
