### ISSUE TITLE
VS 2022

### ISSUE THREAD

**Issue by therealzoomgod** [oleg-shilo/PyMap.VSIX#3]
Will you be updating this for 2022 ?
Also showing function decorators would be a great addition.

If your no longer interested in developing this would you make the previous versions source available ?

Really have become hooked on having this, so useful on big projects

Thanks

**Comment by oleg-shilo** [comment]
I was not sure about the extension's popularity so I did not pay much attention to maintaining it.

Migrating to VS2022 is quite simple. I can have a look at it in a week or two.

If you want to give it a try by yourself then the starting codebase will be this very repository (https://github.com/oleg-shilo/PyMap.VSIX/tree/master/PyMap). This codebase builds into VS2017 and VS2019 IDE. For VS2022 the project structure will need to be changed. But it will need no other cod echanges

**Comment by therealzoomgod** [comment]
I did not realize the source was here but I am not much of a C# programmer, C/C++ I could handle.

No rush, if you can do it I can wait.  It's an outstanding aide for those working on big python projects, no idea why they havn't incorporate this to the python toolkit.

Thanks for the quick response Oleg !

**Comment by therealzoomgod** [comment]
I took a shot at updating it.  I just used nuget to update packages, removed the old manifest entry and created a new one for VS 2022 community.  Seems to work fine.

Thanks

**Comment by oleg-shilo** [comment]
Can you please just create a pull request with the new manifest so I can republished ..

**Comment by therealzoomgod** [comment]
Done but it does specify Community Edition, I followed a MS doc on migrating a vsix to 2022.  Other editions may need added to the manifest.

**Comment by oleg-shilo** [comment]
Done. Published on VS Marketplace
