### ISSUE TITLE
feature request: private icons

### ISSUE THREAD

**Issue by pygamegirl** [oleg-shilo/PyMap.VSIX#5]
Hi

Thank you so much for this extension! I use it all the time for Python but also for C#.

I saw there are no separate icons for private functions or variables.
Could you please add this? See screenshot.
You can see private methods or variables have the little "lock" icon. It could be useful if this was added.

![afbeelding](https://user-images.githubusercontent.com/121575902/210099342-5d971d26-3450-468f-84d2-1d47d9a7330a.png)

**Comment by oleg-shilo** [comment]
will do. not a prob
