### ISSUE TITLE
GUI Layout issue

### ISSUE THREAD

**Issue by rsunde** [oleg-shilo/PyMap.VSIX#8]
Poor layout design, cuts off Auto-Synch

I would also just call it Auto-Sync, which is a more common way of writing Synchronize.

![image](https://github.com/oleg-shilo/PyMap.VSIX/assets/3204741/12d1679a-7024-4fbe-9d96-604637445e92)

**Comment by oleg-shilo** [comment]
Thxs. Indeed there is a mistake in the alignment of the settings panel.
Will be fixed in the very next release
