### ISSUE TITLE
Display Regions somehow

### ISSUE THREAD

**Issue by rsunde** [oleg-shilo/PyMap.VSIX#9]
Is it possible to somehow show that things are inside a region in the outline?

Not as a tree, 

but just possible draw thin lines above and under? color background? maybe even make a little collapsible box around ??

![image](https://github.com/oleg-shilo/PyMap.VSIX/assets/3204741/9edc9302-e543-4aee-9cf2-5f3d7d2f3c52)

**Comment by rsunde** [comment]
Excuse the poor photoshop skills,

imagine like a bounding box for the items in the list, but the box is hardly noticeable, 
maybe with options the region title could be shown, or not, the region could just be a thin box or colored background, or something, I dunno really, just have an idea at the moment


![image](https://github.com/oleg-shilo/PyMap.VSIX/assets/3204741/eb81b089-9eeb-4812-b329-fa9c269e4a41)

**Comment by oleg-shilo** [comment]
Done.
Release v2.1.3.0
It will look like this:
![image](https://github.com/oleg-shilo/PyMap.VSIX/assets/16729806/3bdbed2e-a687-4e71-abc4-6eb67346f574)

**Comment by rsunde** [comment]
I F/&#"%NG LOVE IT!! ;)
